package sqliteadmin

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

func TestS3SignatureAWSExamples(t *testing.T) {
	// Published AWS test vectors, not signatures generated by this code:
	// https://docs.aws.amazon.com/AmazonS3/latest/developerguide/sig-v4-header-based-auth.html
	cfg := S3Config{AccessKeyID: "AKIAIOSFODNN7EXAMPLE", SecretAccessKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY", Region: "us-east-1"}
	for _, tc := range []struct{ path, rangeHeader, signature string }{
		{"/test.txt", "bytes=0-9", "f0e8bdb87c964420e857bd35b5d6ed310bd44f0170aba48dd91039c6036bdb41"},
		{"/?prefix=J&max-keys=2", "", "34b48302e7b5fa45bde8084f4b7868a86f0a534bc59db6670ed5711ef69dc6f7"},
	} {
		r, err := http.NewRequest("GET", "https://examplebucket.s3.amazonaws.com"+tc.path, nil)
		if err != nil {
			t.Fatal(err)
		}
		if tc.rangeHeader != "" {
			r.Header.Set("Range", tc.rangeHeader)
		}
		signS3(r, cfg, hashHex(nil), time.Date(2013, 5, 24, 0, 0, 0, 0, time.UTC))
		if !strings.HasSuffix(r.Header.Get("Authorization"), "Signature="+tc.signature) {
			t.Fatalf("incorrect AWS signature: %s", r.Header.Get("Authorization"))
		}
	}
}

func TestS3EnvironmentConfiguration(t *testing.T) {
	for _, key := range []string{"ENDPOINT", "REGION", "BUCKET", "PREFIX", "ACCESS_KEY_ID", "SECRET_ACCESS_KEY", "SESSION_TOKEN"} {
		t.Setenv("SQLITEADMIN_S3_"+key, "")
	}
	if s, err := newS3Store(Config{Path: "app.db"}); s != nil || err != "" {
		t.Fatal("S3 should be hidden without configuration")
	}
	t.Setenv("SQLITEADMIN_S3_BUCKET", "test-bucket")
	if s, err := newS3Store(Config{}); s != nil || !strings.Contains(err, "SQLITEADMIN_S3_ENDPOINT") {
		t.Fatal("incomplete config should leave local backups usable")
	}
	t.Setenv("SQLITEADMIN_S3_ENDPOINT", "https://storage.example")
	t.Setenv("SQLITEADMIN_S3_ACCESS_KEY_ID", "key")
	t.Setenv("SQLITEADMIN_S3_SECRET_ACCESS_KEY", "secret")
	s, err := newS3Store(Config{Path: "app.db"})
	if s == nil || err != "" || s.cfg.Region != "us-east-1" || s.cfg.Prefix != "sqliteadmin/app.db/" {
		t.Fatalf("S3 config: %s", err)
	}
	t.Setenv("SQLITEADMIN_S3_ENDPOINT", "https://key:secret@storage.example")
	if s, err := newS3Store(Config{}); s != nil || strings.Contains(err, "key:secret") {
		t.Fatal("invalid endpoint or credentials exposed")
	}
}

func TestS3PaginatedListing(t *testing.T) {
	name := "manual-20260101T000000.000000000Z-123456abcdef.sqlite"
	requests := 0
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		requests++
		if r.URL.Query().Get("continuation-token") == "" {
			fmt.Fprint(w, `<ListBucketResult><IsTruncated>true</IsTruncated><NextContinuationToken>next+/=</NextContinuationToken></ListBucketResult>`)
			return
		}
		if r.URL.Query().Get("continuation-token") != "next+/=" {
			t.Error("continuation token changed")
		}
		fmt.Fprintf(w, `<ListBucketResult><IsTruncated>false</IsTruncated><Contents><Key>prefix/%s</Key><Size>42</Size><LastModified>2026-01-01T00:00:00Z</LastModified></Contents><Contents><Key>another-db/%s</Key></Contents></ListBucketResult>`, name, name)
	}))
	defer server.Close()
	s, msg := newS3Store(Config{S3: &S3Config{Endpoint: server.URL, Bucket: "bucket", Prefix: "prefix", AccessKeyID: "key", SecretAccessKey: "secret"}})
	if msg != "" {
		t.Fatal(msg)
	}
	list, err := s.list(context.Background())
	if err != nil || len(list) != 1 || requests != 2 || list[0].Name != name {
		t.Fatalf("pagination: %v %v", list, err)
	}
}

func TestBackupCancellationFinishes(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	calls, finished := 0, 0
	err := stepBackup(ctx, func() (bool, error) { calls++; cancel(); return false, nil }, func() error { finished++; return nil })
	if !errors.Is(err, context.Canceled) || calls != 1 || finished != 1 {
		t.Fatalf("cancel/rollback cleanup: %v %d %d", err, calls, finished)
	}
}
